name: Call reusable workflow example

on:
  pull_request:
    branches:
      - main
      - features/*
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  run-labeler:
    uses: ./.github/workflows/reusable-infra.yml
    # uses: mikolajbb2002/static-web-app-deployment/.github/workflows/reusable-infra.yml@main
    with:
      config-path: .github/labeler.yml
      environment: staging
      component: static-web
      auto-apply: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
